@base_url = http://localhost
@port = 3000
@url = {{base_url}}:{{port}}

### Login 
POST {{url}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@email.com",
    "password": "password"
}

### GET profile
GET  {{url}}/user/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwic3ViIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsImlhdCI6MTY2Nzc0MjA3MSwiZXhwIjoxNjY4MzQyMDcxLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJpc3MiOiJwYXNzcG9ydC1qd3QifQ.92sHQvDSxiM7HEWAAtNIBqXQpcbYjjZBLwj_vYVYyhc

### GET response user
GET  {{url}}/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwic3ViIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsImlhdCI6MTY2Nzc0MTcyMCwiZXhwIjoxNjY4MzQxNzIwLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJpc3MiOiJwYXNzcG9ydC1qd3QifQ.Xgv58Zl5lFcO_sXsF1zloHJgJWhnP4TJYOm4qN-sjd0