@base_url = http://localhost
@port = 3000
@url = {{base_url}}:{{port}}

### GET index route
GET {{url}} HTTP/1.1
Content-Type: application/json

### GET stock
GET {{url}}/stock HTTP/1.1

### GET stock by name
GET {{url}}/stock?name=Test HTTP/1.1

### GET stock by id
GET {{url}}/stock/1 HTTP/1.1

### Create stock 
POST {{url}}/stock HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "price": 25.8,
    "stock": 1234
}

### Create stock pass image
POST {{url}}/stock HTTP/1.1 
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

test
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

25.8
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock"

1234
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="profile.png"
Content-Type: image/png

< ./src/assets/mock/profile.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### PATCH stock 
PATCH {{url}}/stock/128 HTTP/1.1
Content-Type: application/json

{
    "name": "88888",
    "price": 8
}

### PATCH stock pass image
PATCH {{url}}/stock/128 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

test
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

25.8
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock"

1234
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="profile.png"
Content-Type: image/png

< ./src/assets/mock/profile.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### PUT stock 
PUT {{url}}/stock/128 HTTP/1.1
Content-Type: application/json

{
    "name": "aaaa",
    "price": 9
}

### PUT stock pass image
PUT {{url}}/stock/128 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

test
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

25.8
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock"

1234
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="profile.png"
Content-Type: image/png

< ./src/assets/mock/profile.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### DELETE stock 
DELETE {{url}}/stock/127 HTTP/1.1